# Generated by Django 4.2.3 on 2023-09-23 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('claim_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('claim_payout', models.FloatField(null=True)),
                ('liability_claim_percentage', models.FloatField(null=True)),
                ('policy_channel', models.CharField(max_length=255, null=True)),
                ('third_party_policy', models.CharField(max_length=255, null=True)),
                ('fraud', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50, null=True)),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('user_image', models.ImageField(default=None, null=True, upload_to='uploads')),
                ('client_password', models.CharField(max_length=255, null=True)),
                ('client_confirm_password', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(choices=[('general_user', 'general_user'), ('admin', 'admin'), ('authority', 'authority'), ('staff', 'staff'), ('investigator', 'investigator')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_info',
            fields=[
                ('phone_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(max_length=30)),
                ('email', models.EmailField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_info',
            fields=[
                ('vehicle_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('age', models.FloatField(null=True)),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('number_of_claims_five_years', models.IntegerField(null=True)),
                ('marital_status', models.CharField(max_length=255, null=True)),
                ('living_status', models.CharField(max_length=255, null=True)),
                ('address_change', models.CharField(max_length=255, null=True)),
                ('claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.claims')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(default=None, null=True, upload_to='uploads')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('weight', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('vehicle_age', models.FloatField(null=True)),
                ('claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.claims')),
                ('vehicle_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.driver_info')),
            ],
        ),
        migrations.CreateModel(
            name='Accident_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witness', models.BooleanField(null=True)),
                ('accident_loaction', models.CharField(max_length=255, null=True)),
                ('claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.claims')),
                ('vehicle_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='myapp.driver_info')),
            ],
        ),
    ]
